config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resources :listing_integrations, as: :integrations
  end

  resources :integrations

  devise_for :users

  root to: "pages#home"
end

app/models/listing_integration.rb
require "capybara"
require "capybara/poltergeist"

class ListingIntegration < ApplicationRecord
  belongs_to :listing
  belongs_to :integration

  scope :published, -> { where("identifier is not null") }
  scope :not_published, -> { where("identifier is null") }

  def name
    Integration::INTEGRATIONS[type]
  end

  def session
    @session ||= Capybara::Session.new(:poltergeist_no_js)
  end
end

app/models/listing_integrations/achou_mudou.rb
class ListingIntegrations::AchouMudou < ListingIntegration
  LOGIN_URL = "https://www.achoumudou.com.br/login.php"
  NEW_LISTING_URL = "https://www.achoumudou.com.br/imovel-cadastro.php"

  TRANSACTION_TYPE_MODIFICATIONS = {
    "Aluguel" => "Alugar",
    "Aluguel por Temporada" => "Alugar por temporada",
    "Venda" => "Vender"
  }

  TYPE_MODIFICATIONS = {
    "Fazenda" => "Rural"
  }

  REQUIRED_FIELDS = [
    :transaction_type, :listing_type, :title, :district, :state, :city, :description
  ]

  def fill_form
    session.within("#miolo") do
      session.select TRANSACTION_TYPE_MODIFICATIONS[self.listing.transaction_type], from: "selint"
      if TYPE_MODIFICATIONS[self.listing.listing_type]
        session.select TYPE_MODIFICATIONS[self.listing.listing_type], from: "seltip"
      else
        session.select self.listing.listing_type, from: "seltip"
      end
      session.first("input[name='frmtit']").set self.listing.title
      session.fill_in "inpval", with: self.listing.price
      session.first("textarea[name='frmdes']").set self.listing.description
      session.first("input[name='frmend']").set self.listing.street
      session.select self.listing.state, from: "cadest"
      session.select I18n.transliterate(self.listing.city.upcase), from: "cadcid"
      session.select self.listing.bedrooms, from: "selqua"
      session.first("input[name='frmbai']").set self.listing.district
      session.click_on "butcon"
    end
  end

  def destroy_listing
    login
    response = session.visit destroy_listing_url
    if response["status"] == "success"
      self.destroy
    end
  end

  def create_listing
    login
    session.visit NEW_LISTING_URL
    fill_form
    get_identifier
  end

  def update_listing
    login
    session.visit listing_edit_url
    fill_form
  end

  def get_identifier
    cod = session.first(".boxval").first("span").text.gsub(/\D/,"")
    self.update_attribute :identifier, cod
  end

  def login
    session.visit LOGIN_URL
    session.first("input[name='usuario']").set self.integration.username
    session.first("input[name='senha']").set self.integration.password
    session.click_on "butcon"
  end

  def destroy_listing_url
    "https://www.achoumudou.com.br/funcoes/excluir.php?codigo=#{self.identifier}"
  end

  def listing_url
    "https://www.achoumudou.com.br/#{self.identifier}/titulo" 
  end

  def listing_edit_url
    "https://www.achoumudou.com.br/imovel-altera.php?codigo=#{self.identifier}"
  end
end

app/models/listing_integrations/portal_rj_imoveis.rb
class ListingIntegrations::PortalRjImoveis < ListingIntegration
  LOGIN_URL = "http://www.portalrjimoveis.com.br/restrito.php"
  NEW_LISTING_URL = "http://www.portalrjimoveis.com.br/anunciante/adicionar-cad.php"

  TYPE_MODIFICATIONS = {
    "Fazenda" => "Rural"
  }

  REQUIRED_FIELDS = [
    :reference, :transaction_type, :listing_type, :title, :description, :price,
    :square_feet, :state, :city, :district
  ]

  def fill_create_form
    session.fill_in "CODIGOREFERENCIA", with: self.listing.reference
    session.choose(self.listing.renting? ? "FINALIDADE_2" : "FINALIDADE_1")
    if TYPE_MODIFICATIONS[self.listing.listing_type]
      session.select TYPE_MODIFICATIONS[self.listing.listing_type], from: "TIPOIMOVEL"
    else
      session.select self.listing.listing_type, from: "TIPOIMOVEL"
    end
    session.fill_in "TITULO", with: self.listing.title
    session.fill_in "DESCRICAO", with: self.listing.description
    session.fill_in "PRECO", with: self.listing.price
    session.fill_in "AREA", with: self.listing.square_feet
    session.select "RJ", from: "ESTADO"
    session.select self.listing.city, from: "CIDADE"
    session.select self.listing.bedrooms, from: "DORMITORIOS"
    session.select self.listing.bathrooms, from: "BANHEIROS"
    session.select self.listing.suites, from: "SUITES"
    session.select self.listing.parking_spaces, from: "VAGAS"
    session.fill_in "BAIRRO", with: self.listing.district
    session.fill_in "CEP", with: self.listing.zipcode
    session.click_on "KT_Insert1"
  end

  def fill_update_form
    session.fill_in "CODIGOREFERENCIA_1", with: self.listing.reference
    session.choose(self.listing.renting? ? "FINALIDADE_1_2" : "FINALIDADE_1_1")
    if TYPE_MODIFICATIONS[self.listing.listing_type]
      session.select TYPE_MODIFICATIONS[self.listing.listing_type], from: "TIPOIMOVEL"
    else
      session.select self.listing.listing_type, from: "TIPOIMOVEL"
    end
    session.fill_in "TITULO_1", with: self.listing.title
    session.fill_in "DESCRICAO_1", with: self.listing.description
    session.fill_in "PRECO_1", with: self.listing.price
    session.fill_in "AREA_1", with: self.listing.square_feet
    session.select "RJ", from: "ESTADO"
    session.select self.listing.city, from: "CIDADE"
    session.select self.listing.bedrooms, from: "DORMITORIOS"
    session.select self.listing.bathrooms, from: "BANHEIROS"
    session.select self.listing.suites, from: "SUITES"
    session.select self.listing.parking_spaces, from: "VAGAS"
    session.fill_in "BAIRRO_1", with: self.listing.district
    session.fill_in "CEP_1", with: self.listing.zipcode
    session.first("input[name='KT_Update1']").click
  end

  def destroy_listing
    login
    session.visit listing_edit_url
    session.first("input[name='KT_Delete1']").click
    if session.text.include?("Exclusão realizada com sucesso")
      self.destroy
    end
  end

  def create_listing
    login
    session.visit NEW_LISTING_URL
    fill_create_form
    get_identifier
  end

  def update_listing
    login
    session.visit listing_edit_url
    fill_update_form
  end

  def get_identifier
    pkey = session.find("#imovel_foto")[:href].match(/IMOVEL_PKEY=(.*)/)[1]
    self.update_attribute :identifier, pkey
  end

  def login
    session.visit LOGIN_URL
    session.fill_in "kt_login_user", with: self.integration.username
    session.fill_in "kt_login_password", with: self.integration.password
    session.click_on "kt_login1"
  end

  def listing_url
    "http://www.portalrjimoveis.com.br/imoveis.php?imovel=#{self.identifier}" 
  end

  def listing_edit_url
    "http://www.portalrjimoveis.com.br/anunciante/editar.php?IMOVEL_PKEY=#{self.identifier}"
  end
end

app/models/listing_integrations/proprietario_direto.rb
class ListingIntegrations::ProprietarioDireto < ListingIntegration
  LOGIN_URL = "https://www.proprietariodireto.com.br/"
  NEW_LISTING_URL = "https://www.proprietariodireto.com.br/imoveis-direto-com-proprietario-cadastrar-imovel"

  REQUIRED_FIELDS = [
    :title, :city, :state, :price, :square_feet, :bedrooms, :phone, :description,
    :district, :street
  ]

  def fill_form
    session.first("input[name='title']").set self.listing.title
    if self.listing.selling?
      session.first("input[name='sale']").set self.listing.price
    else
      session.first("input[name='rent']").set self.listing.price
    end
    session.first("select[name='kind']").set(self.listing.listing_type)
    session.first("input[name='area']").set self.listing.square_feet
    session.first("input[name='room']").set self.listing.bedrooms
    session.first("input[name='vacancies']").set self.listing.parking_spaces
    session.first("input[name='phone']").set self.listing.phone
    session.first("textarea[name='desc']").set self.listing.description
    session.first("input[name='address']").set "#{self.listing.city} #{self.listing.state}"
    session.first("input[name='address']").native.send_keys(:return)
    # session.first("input[name='city']").set self.listing.city
    # session.first("input[name='city']").native.send_keys(:return)
    session.first("input[name='route']").set self.listing.street
    session.first("input[name='neighborhood']").set self.listing.district
    session.first("#confirmed").click
    session.first("button[name='save']").click
  end

  def destroy_listing
    login
    response = session.visit listing_edit_url
    session.click_on "delete-property"
    session.find("input[value='Sim']").click
    if session.current_path == "/imoveis"
      self.destroy
    end
  end

  def create_listing
    login
    session.visit NEW_LISTING_URL
    fill_form
    get_identifier
  end

  def update_listing
    login
    session.visit listing_edit_url
    fill_form
  end

  def login
    session.visit LOGIN_URL
    session.all("input[name='email']")[0].set self.integration.username
    session.all("input[name='password']")[0].set self.integration.password
    session.all("input[name='email']", visible: false)[1].set self.integration.username
    session.all("input[name='password']", visible: false)[1].set self.integration.password
    session.click_on("Fazer login")
  end

  def get_identifier
    cod = session.all(".list-item-widget").last.find("a")[:href].match(/properties\/(.*)\/edit/)[1]
    self.update_attribute :identifier, cod
  end

  def listing_edit_url
    "https://www.proprietariodireto.com.br/properties/#{self.identifier}/edit"
  end

  def listing_url
    "https://www.proprietariodireto.com.br/properties/#{self.identifier}/edit"
  end
end

app/models/listing_integrations/viva_local.rb
class ListingIntegrations::VivaLocal < ListingIntegration
  LOGIN_URL = "http://www.vivalocal.com/login.php"
  NEW_LISTING_URL = "http://post.vivalocal.com/"

  TRANSACTION_TYPE_MODIFICATIONS = {
    "Aluguel" => "Aluguel Imóveis",
    "Venda" => "Venda Imóveis",
    "Aluguel por Temporada" => "Aluguel Temporada"
  }
  REQUIRED_FIELDS = [
    :transaction_type, :state, :title, :description, :square_feet, :street, :city, :state
  ]
  

  def fill_form
    session.select self.listing.state_full, from: "postingGeo_1"
    session.fill_in "title", with: self.listing.title
    session.fill_in "detail", with: self.listing.description

    if self.listing.business?
      session.select "Imóveis comerciais", from: "posting_category_select"
      if self.listing.renting?
        session.find("input[value='storage_parking']").click
      else
        session.find("input[value='office_commercial']").click
      end
    elsif self.listing.farm?
      session.select "Terrenos e Lotes a Venda", from: "posting_category_select"
      session.first("input[name='price[price]']").set self.listing.price
    elsif self.listing.renting? || self.listing.renting_season?
      session.select TRANSACTION_TYPE_MODIFICATIONS[self.listing.transaction_type], from: "posting_category_select"
      session.first("input[name='price[rent]']").set self.listing.price
      session.select self.listing.bedrooms, from: "id_rooms"
      session.fill_in "id_surface", with: self.listing.square_feet
      session.fill_in "id_geo_address", with: "#{self.listing.street}, #{self.listing.city}, #{self.listing.state}"
    elsif self.listing.selling?
      session.select TRANSACTION_TYPE_MODIFICATIONS[self.listing.transaction_type], from: "posting_category_select"
      session.first("input[name='price[price]']").set self.listing.price
      session.select self.listing.bedrooms, from: "id_rooms"
      session.fill_in "id_surface", with: self.listing.square_feet
      session.fill_in "id_geo_address", with: "#{self.listing.street}, #{self.listing.city}, #{self.listing.state}"
    end

    session.check "term_checkbox"
    session.click_on "publish_button"
  end

  def destroy_listing
  end

  def create_listing
    login
    session.visit NEW_LISTING_URL
    fill_form
    get_identifier
  end

  def update_listing
    login
    session.visit listing_edit_url
    fill_form
  end

  def login
    binding.pry
    session.visit LOGIN_URL
    session.fill_in "email", with: self.integration.username
    session.fill_in "password", with: self.integration.password
    session.click_on("Entrar")
  end

  def get_identifier
  end

  def listing_edit_url
    "https://www.proprietariodireto.com.br/properties/#{self.identifier}/edit"
  end

  def listing_url
    "https://www.proprietariodireto.com.br/properties/#{self.identifier}/edit"
  end  
end

app/controllers/listing_integrations_controller.rb
class ListingIntegrationsController < ApplicationController
  def index
    @listing = current_user.listings.find(params[:listing_id])
  end

  def new
    @listing = current_user.listings.find(params[:listing_id])
    @listing.integrations_possible_to_select.map do |integration|
      @listing.listing_integrations.find_or_initialize_by(integration_id: integration.id)
    end
  end

  def create
    @listing = current_user.listings.find(params[:listing_id])
    @listing.update_attributes(listing_params)
    @listing.publish_integrations
    redirect_to listing_integrations_path(@listing)
  end

  def destroy
    @listing = current_user.listings.find(params[:listing_id])
    @listing_integration = @listing.listing_integrations.find(params[:id])
    @listing_integration.destroy_listing
    redirect_to listing_integrations_path(@listing)
  end

  private

    def listing_params
      params.require(:listing).permit!
    end
end

app/views/listing_integrations/_table.html.haml
- if integrations.any?
  %h4= title
  #spinner
  %table.table.table-striped
    %tr
      %th Nome
      %th Site
      - if status == "complete"
        %th
      - integrations.each do |integration|
        %tr
          %td= Integration::INTEGRATIONS[integration.type]
          %td= link_to integration.listing_url, integration.listing_url, target: "_blank"
          - if status == "complete"
            %td
              = link_to "x", listing_integration_path(@listing, integration), method: :delete, data: { confirm: "Tem certeza?" }, class: "btn btn-danger btn-xs"

app/views/listing_integrations/index.html.haml
.row
  .col-md-10.col-md-offset-1
    .row
      .col-sm-8
        %h3
          = link_to "Meus Anúncios", listings_path
          = "/"
          = @listing.title
      .col-sm-4.text-right
        = link_to "Ver Dados", edit_listing_path(@listing), class: "btn btn-primary btn-right"
    %hr
    - if @listing.listing_integrations.any?
      = render "listing_integrations/table", integrations: @listing.integrations_completed, title: "Integrações Completas", status: "complete"
      = render "listing_integrations/table", integrations: @listing.integrations_publishing, title: "Integrações em Criação", status: "pending"
      = render "listing_integrations/table", integrations: @listing.integrations_updating, title: "Integrações em Atualização", status: "pending"
      = render "listing_integrations/table", integrations: @listing.integrations_failed, title: "Integrações Falhas", status: "failed"
    - else
      .well.text-center
        %h4 Nenhuma integração para esse Anúncio.

app/views/listing_integrations/new.html.haml
.row
  .col-md-10.col-md-offset-1
    .row
      .col-sm-8
        %h3
          = link_to "Meus Anúncios", listings_path
          = "/"
          = link_to @listing.title, edit_listing_path(@listing)
          = "/"
          Integrações
    %hr

    = form_for @listing, url: listing_integrations_path(@listing), method: :post do |f|
      - if @listing.integrations_possible_to_select.any?
        %h4 Integrações Possíveis
        .well
          = check_box_tag :check_all 
          Marcar tudo
          %hr
          = f.fields_for :listing_integrations do |i_f|
            .row
              .col-md-6
                - listing_integration = i_f.object
                - integration = listing_integration.integration
                = i_f.hidden_field :type, value: integration.name
                = i_f.check_box :integration_id, { checked: listing_integration.id.present? }, integration.id
                = integration.site_name
              .col-md-6.text-right
                %small
                  Ação:
                  = listing_integration.identifier ? "atualizar" : "criar"
        %p
          • Os anúncios podem demorar até 1 hora para serem publicados em todos os sites. 
        %p
          • Você poderá acompanhar em tempo real quais já foram publicados através da página de cada anúncio.

      - if @listing.integrations_impossible_to_select.any?
        %h4 Integrações Impossíveis
        .well
          - @listing.integrations_impossible_to_select.each do |integration|
            = integration.site_name
            = "(#{@listing.missing_fields(integration).join(",")})"
        %p
          • Isso ocorre porque você não inseriu detalhes suficientes para o anúncio ser cadastrado nos sites listados.

      .text-right
        = link_to "Voltar", edit_listing_path(@listing), class: "btn btn-default"
        - if @listing.integrations_possible_to_select.any?
          = f.submit "Publicar!", class: "btn btn-success"