config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resources :listing_integrations, as: :integrations
  end

  resources :integrations

  devise_for :users

  root to: "pages#home"
end

app/models/listing.rb
class Listing < ApplicationRecord
  include Listing::Integrations

  has_many :listing_integrations
  has_many :images
  belongs_to :user
  accepts_nested_attributes_for :listing_integrations, allow_destroy: true

  TYPES = [
    "Apartamento",
    "Casa",
    "Comercial",
    "Cobertura",
    "Flat",
    "Kitchenette",
    "Loft",
    "Sobrado",
    "Terreno",
    "Fazenda",
    "Chácara"
  ]

  TRANSACTION_TYPES = [
    "Aluguel",
    "Venda",
    "Aluguel por Temporada"
  ]

  STATES = {
    "Acre" => "AC",
    "Alagoas" => "AL",
    "Amapá" => "AP",
    "Amazonas" => "AM",
    "Bahia" => "BA",
    "Ceará" => "CE",
    "Distrito Federal" => "DF",
    "Espírito Santo" => "ES",
    "Goiás" => "GO",
    "Maranhão" => "MA",
    "Mato Grosso" => "MT",
    "Mato Grosso do Sul" => "MS",
    "Minas Gerais" => "MG",
    "Pará" => "PA",
    "Paraíba" => "PB",
    "Paraná" => "PR",
    "Pernambuco" => "PE",
    "Piauí" => "PI",
    "Roraima" => "RR",
    "Rondônia" => "RO",
    "Rio de Janeiro" => "RJ",
    "Rio Grande do Norte" => "RN",
    "Rio Grande do Sul" => "RS",
    "Santa Catarina" => "SC",
    "São Paulo" => "SP",
    "Sergipe" => "SE",
    "Tocantins" => "TO"
  }

  def full_address
    "#{city}/#{state}"
  end

  def selling?
    self.transaction_type == "Venda"
  end

  def renting?
    self.transaction_type == "Aluguel"
  end

  def renting_season?
    self.transaction_type == "Aluguel por Temporada"
  end

  def state_full
    STATES.key(self.state)
  end

  def business?
    self.listing_type = "Comercial"
  end

  def farm?
    self.listing_type = "Fazenda"
  end
end

app/models/listing/integrations.rb
module Listing::Integrations
  extend ActiveSupport::Concern
  
  included do
    def publish_integrations
      self.integrations_possible_to_publish.each do |listing_integration|
        Delayed::Job.enqueue(
          PublishIntegrationJob.new(listing_integration.id), queue: "queue_publish_#{listing_integration.id}"
        )
      end    
    end

    def integration_possible?(integration)
      !integration.name.constantize::REQUIRED_FIELDS.any? { |field| self.send(field).blank? }
    end

    def missing_fields(integration)
      integration.name.constantize::REQUIRED_FIELDS.select { |field| self.send(field).blank? }
    end

    def integrations_possible_to_select
      self.user.integrations.select { |integration| self.integration_possible?(integration) }
    end

    def integrations_impossible_to_select
      self.user.integrations.select { |integration| !self.integration_possible?(integration) }
    end

    def integrations_possible_to_publish
      self.listing_integrations.select { |li| self.integration_possible?(li.integration) }
    end

    def integration_impossible_to_publish
      self.listing_integrations.select { |li| !self.integration_possible?(li.integration) }
    end

    def integrations_failed
      self.listing_integrations.not_published - self.integrations_publishing
    end

    def integrations_completed
      self.listing_integrations.published - self.integrations_updating
    end

    def integrations_publishing
      self.listing_integrations.not_published.select do |integration| 
        Delayed::Job.find_by(queue: "queue_publish_#{integration.id}")
      end
    end

    def integrations_updating
      self.listing_integrations.published.select do |integration| 
        Delayed::Job.find_by(queue: "queue_publish_#{integration.id}")
      end
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = current_user.listings
  end

  def new
    @listing = current_user.listings.build
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def create
    @listing = current_user.listings.build(listing_params)

    if @listing.save
      redirect_to new_listing_integration_path(@listing)
    else
      render :new
    end
  end

  def update
    @listing = current_user.listings.find(params[:id])

    if @listing.update_attributes(listing_params)
      redirect_to new_listing_integration_path(@listing)
    else
      render :edit
    end
  end

  def destroy
    @listing = current_user.listings.find(params[:id])
    @listing.destroy
    redirect_to listings_path, notice: "Publicação removida com sucesso."
  end

  private

    def listing_params
      params.require(:listing).permit!
    end
end

app/views/listings/_form.html.haml
= form_for @listing do |f|
  .row
    .col-sm-6
      .form-group
        .row
          .col-sm-4
            = f.label :title, "Título", class: "control-label"
          .col-sm-8
            = f.text_field :title, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :description, "Descrição", class: "control-label"
          .col-sm-8
            = f.text_area :description, class: "form-control", rows: 3
      .form-group
        .row
          .col-sm-4
            = f.label :listing_type, "Tipo do Imóvel", class: "control-label"
          .col-sm-8
            = f.select :listing_type, options_for_select(Listing::TYPES, @listing.listing_type), { prompt: "Selecione" }, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :transaction_type, "Finalidade", class: "control-label"
          .col-sm-8
            = f.select :transaction_type, options_for_select(Listing::TRANSACTION_TYPES, @listing.transaction_type), { prompt: "Selecione" }, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :reference, "Código / Referência", class: "control-label"
          .col-sm-8
            = f.text_field :reference, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :price, "Preço", class: "control-label"
          .col-sm-8
            = f.text_field :price, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :bedrooms, "Quartos", class: "control-label"
          .col-sm-8
            = f.select :bedrooms, options_for_select(1..10, @listing.bedrooms), { include_blank: "Selecione" }, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :bathrooms, "Banheiros", class: "control-label"
          .col-sm-8
            = f.select :bathrooms, options_for_select(1..10, @listing.bathrooms), { include_blank: "Selecione" }, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :suites, "Suites", class: "control-label"
          .col-sm-8
            = f.select :suites, options_for_select(1..10, @listing.suites), { include_blank: "Selecione" }, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :parking_spaces, "Vagas", class: "control-label"
          .col-sm-8
            = f.select :parking_spaces, options_for_select(1..10, @listing.parking_spaces), { include_blank: "Selecione" }, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :square_feet, "Área útil (m²)", class: "control-label"
          .col-sm-8
            = f.text_field :square_feet, class: "form-control"
    .col-sm-6
      .form-group
        .row
          .col-sm-4
            = f.label :state, "Estado", class: "control-label"
          .col-sm-8
            = f.text_field :state, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :city, "Cidade", class: "control-label"
          .col-sm-8
            = f.text_field :city, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :district, "Bairro", class: "control-label"
          .col-sm-8
            = f.text_field :district, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :street, "Rua", class: "control-label"
          .col-sm-8
            = f.text_field :street, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :number, "Número", class: "control-label"
          .col-sm-8
            = f.text_field :number, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :complement, "Complemento", class: "control-label"
          .col-sm-8
            = f.text_field :complement, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :zipcode, "CEP", class: "control-label"
          .col-sm-8
            = f.text_field :zipcode, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :phone, "Telefone", class: "control-label"
          .col-sm-8
            = f.text_field :phone, class: "form-control"
      %p
        • Preencha o máximo de campos possívels para o anúncio ser publicado na maior quantidade de sites.
      .pull-right
        - if @listing.new_record?
          = f.submit "Criar e definir integrações", class: "btn btn-success"
        - else
          = f.submit "Atualizar", class: "btn btn-success"

app/views/listings/edit.html.haml
.row
  .col-md-10.col-md-offset-1
    .row
      .col-sm-8
        %h3
          = link_to "Meus Anúncios", listings_path
          = "/"
          = @listing.title
      .col-sm-4.text-right
        = link_to "Ver Integrações", listing_integrations_path(@listing), class: "btn btn-primary btn-right"
    %hr
    = render "form"

app/views/listings/index.html.haml
.row
  .col-md-10.col-md-offset-1
    .row
      .col-sm-8
        %h3 Meus Anúncios
      .col-sm-4.text-right
        = link_to "Novo anúncio", new_listing_path, class: "btn btn-success btn-right"
    %hr
    %table.table.table-striped
      %tr
        %th Referência
        %th Título
        %th Transação
        %th Tipo
        %th Cidade
        %th Preço
        %th Integrações
        %th
      - @listings.each do |listing|
        %tr
          %td= listing.reference
          %td= link_to listing.title, edit_listing_path(listing)
          %td= listing.transaction_type
          %td= listing.listing_type
          %td= listing.full_address
          %td= number_to_currency listing.price, unit: "R$ ", separator: ",", delimiter: "."
          %td
            .label.label-success.label-integration
              = link_to listing.listing_integrations.published.length, listing_integrations_path(listing)
          %td= link_to "x", listing_path(listing), method: :delete, class: "btn btn-danger btn-xs", data: { confirm: "Tem certeza?" }

app/views/listings/new.html.haml
.row
  .col-md-10.col-md-offset-1
    .row
      .col-sm-8
        %h3
          = link_to "Meus Anúncios", listings_path
          = "/"
          Novo Anúncio
    %hr
    = render "form"