config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resources :listing_integrations, as: :integrations
  end

  resources :integrations

  devise_for :users

  root to: "pages#home"
end

app/models/integration.rb
class Integration < ApplicationRecord
  INTEGRATIONS = {
    "ListingIntegrations::PortalRjImoveis" => "Portal RJ Imóveis",
    "ListingIntegrations::AchouMudou" => "Achou Mudou",
    "ListingIntegrations::ProprietarioDireto" => "Proprietário Direto"
  }.freeze

  belongs_to :user

  def fakepassword
    self.password.gsub(/./,"*") if self.password
  end

  def site_name
    Integration::INTEGRATIONS[self.name]
  end
end

app/models/listing/integrations.rb
module Listing::Integrations
  extend ActiveSupport::Concern
  
  included do
    def publish_integrations
      self.integrations_possible_to_publish.each do |listing_integration|
        Delayed::Job.enqueue(
          PublishIntegrationJob.new(listing_integration.id), queue: "queue_publish_#{listing_integration.id}"
        )
      end    
    end

    def integration_possible?(integration)
      !integration.name.constantize::REQUIRED_FIELDS.any? { |field| self.send(field).blank? }
    end

    def missing_fields(integration)
      integration.name.constantize::REQUIRED_FIELDS.select { |field| self.send(field).blank? }
    end

    def integrations_possible_to_select
      self.user.integrations.select { |integration| self.integration_possible?(integration) }
    end

    def integrations_impossible_to_select
      self.user.integrations.select { |integration| !self.integration_possible?(integration) }
    end

    def integrations_possible_to_publish
      self.listing_integrations.select { |li| self.integration_possible?(li.integration) }
    end

    def integration_impossible_to_publish
      self.listing_integrations.select { |li| !self.integration_possible?(li.integration) }
    end

    def integrations_failed
      self.listing_integrations.not_published - self.integrations_publishing
    end

    def integrations_completed
      self.listing_integrations.published - self.integrations_updating
    end

    def integrations_publishing
      self.listing_integrations.not_published.select do |integration| 
        Delayed::Job.find_by(queue: "queue_publish_#{integration.id}")
      end
    end

    def integrations_updating
      self.listing_integrations.published.select do |integration| 
        Delayed::Job.find_by(queue: "queue_publish_#{integration.id}")
      end
    end
  end
end

app/controllers/integrations_controller.rb
class IntegrationsController < ApplicationController
  def index
    @integrations = current_user.integrations
  end

  def new
    @integration = current_user.integrations.build
  end

  def edit
    @integration = Integration.find(params[:id])
  end

  def create
    @integration = current_user.integrations.build(integration_params)

    if @integration.save
      redirect_to integrations_path
    else
      render :new
    end
  end

  def update
    @integration = current_user.integrations.find(params[:id])

    if @integration.update_attributes(integration_params)
      redirect_to integrations_path
    else
      render :edit
    end
  end

  def destroy
    @integration = current_user.integrations.find(params[:id])
    @integration.destroy
    redirect_to integrations_path, notice: "Integração removida com sucesso."
  end

  private

    def integration_params
      params.require(:integration).permit!
    end
end

app/helpers/integrations_helper.rb
module IntegrationsHelper

end

app/views/integrations/_form.html.haml
= form_for @integration.becomes(Integration) do |f|
  .row
    .col-sm-8.col-sm-offset-2
      .form-group
        .row
          .col-sm-4
            = f.label :name, "Site", class: "control-label"
          .col-sm-8
            = f.select :name, options_for_select(Integration::INTEGRATIONS.invert, @integration.name), { include_blank: "Selecione um Site" }, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :username, "Email / Usuário", class: "control-label"
          .col-sm-8
            = f.text_field :username, class: "form-control"
      .form-group
        .row
          .col-sm-4
            = f.label :password, "Senha", class: "control-label"
          .col-sm-8
            = f.password_field :password, class: "form-control"
      %p.text-right
        = f.submit "Salvar", class: "btn btn-success"

app/views/integrations/edit.html.haml
.row
  .col-md-10.col-md-offset-1
    .row
      .col-sm-8
        %h3
          = link_to "Minhas Integrações", integrations_path
          = "/"
          = @integration.site_name
    %hr
    = render "form"

app/views/integrations/index.html.haml
.row
  .col-md-10.col-md-offset-1
    .row
      .col-sm-8
        %h3 Minhas Integrações
      .col-sm-4.text-right
        = link_to "Nova Integração", new_integration_path, class: "btn btn-success btn-right"
    %hr
    %table.table.table-striped
      %tr
        %th Site
        %th Email
        %th Senha
        %th
      - @integrations.each do |integration|
        %tr
          %td= link_to integration.site_name, edit_integration_path(integration)
          %td= integration.username
          %td= integration.fakepassword
          %td= link_to "x", integration_path(integration), method: :delete, class: "btn btn-danger btn-xs", data: { confirm: "Tem certeza?" }

app/views/integrations/new.html.haml
.row
  .col-md-10.col-md-offset-1
    .row
      .col-sm-8
        %h3
          = link_to "Minhas Integrações", integrations_path
          = "/"
          Nova Integração
    %hr
    = render "form"