config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resources :listing_integrations, as: :integrations
  end

  resources :integrations

  devise_for :users

  root to: "pages#home"
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => '/'}
        = image_tag "listings-logo.png"
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li
          = link_to "Meus Anúncios", listings_path
        %li
          = link_to "Minhas Integrações", integrations_path
        %li
          = link_to "Sair", destroy_user_session_path, method: :delete
      - else
        %li
          = link_to "Registrar", new_user_registration_path
        %li
          = link_to "Entrar", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Listing.com.br
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  %body
    = render "layouts/header"
    .container
      = yield